### ISSUE TITLE
Jett & Dubin 

### ISSUE THREAD

**Issue by nniiicc** [sig-cm/JCDL2019#4]
@kfenlon + @organisciak  
- https://github.com/sig-cm/JCDL2019/blob/master/jett-dubin_sigcm_19.pdf

- [x] Overview (2-3 sentence overview of the contribution)
- [x] Feedback (2-3 paragraphs highlighting strengths of the paper. Please note anything that will be valuable for the authors to discuss / present at workshop)

**Comment by organisciak** [comment]
Some of the parts took some deciphering, but overall relevant. Below are initial comments for the authors.

--------

This submission discusses conceptual issues in how LRM defines manifestations and aggregates. Specifically, the bottom-up definition of manifestations as sets of common items brings up complex and tough to reconcile issues. The second issue discussed is the concept of an aggregating manifestation for multiple expressions.

An exploration of the adverse effects of the models introduced in LRM is important to the field, and very relevant to this workshop.

The issue with the redefinition of manifestations is particularly concerning. As you note, the bottom-up definition suggests a bottom-up inheritance of attribute properties, which seems counter to the intent. One angle that I would like to see considered is the generous take - what motivated this choice and how may it be useful in our attempts to model works?

The second issue is more difficult to disentangle, and may need some more thought in preparation for the workshop. You premise the discussion on issues around manifestations that aggregate expressions; however, LRM seems to define the aggregates of expressions as new expressions; the aggregate manifestation is an embodiment of that aggregating expression. This is still a step away from the whole/part work-level relationships in FRBR, just different. The issue with series' still stands though - since the nature of the aggregate seems overly constrained by physical or organizational structure. An article in a magazine can be seen as an item for the article expression itself, as well as part of an item representing an aggregating manifestation for an aggregate expression, but what is it's relationship to articles in the next issue in the magazine? If the full series is not an aggregate expression itself, it seems that the bounds of the aggregate expression are being influenced by physical form in complicating ways.

Overall, good work. I look forward to where the discussion leads.

Typo: exemplifcation
Suggestion: hyphenate issue-level, series-level

**Comment by organisciak** [comment]
@nniiicc, should Katrina and I work together to submit a single set of comments? Or treat it as separate reviews?

**Comment by nniiicc** [comment]
I was thinking we would give submissions 2 reviewed each....And that we would just give participants access to this repo where they could see reviews... Your review is really thorough (thanks!) - let's leave it up to @kfenlon if she wants to add anything.

**Comment by kfenlon** [comment]
This is a great paper, providing deep analysis of an important conceptual model in terms of both ontological and pragmatic implications. It will make a substantial contribution to the workshop, and it portends a super interesting dissertation! I agree with all of Peter's suggestions, and I have a few comments of my own. 

- The paper is technically and intellectually dense, which is awesome! You dive right into the differences between LRM and FRBR, but to clarify things, particularly for non-library folks, it could be helpful to provide a succinct overview of the issues you will be raising. The paper enumerates several different problems with LRM (and a couple of other models). It would be helpful in the intro or conclusion, at the workshop, to offer a unified list (in bullet-point or tabular form) of the distinct but deeply interrelated problems you have identified, e.g.: 
1. LRM does not support plurality of expressions and LRM does not support multiple interpretations of texts 
2. The bottom-up definition of manifestations is inconsistent with the definition of all other top-level entities
3. Attributes of aggregates are not always properties of manifestation sets or their elements
4. Subset relationships violate the cardinality constraint...
Etc.

- Section 3 would be clearer with some concrete examples. It's hard for a simple mind like mine to keep track of series-level vs. issue-level manifestations...  I know from prior encounters with your work that your talks usually deploy beautiful and intricate examples from real library collections to illustrate modeling problems, and I hope this holds true for your workshop talk. In particular, you describe how different problems in the LRM imperil different aspects of description. I'd like to see this made more concrete or vivid.
