### ISSUE TITLE
Thomer et al

### ISSUE THREAD

**Issue by nniiicc** [sig-cm/JCDL2019#6]
@nniiicc + @kfenlon 
- https://github.com/sig-cm/JCDL2019/blob/master/thomer_sigcm_19.pdf

- [x] Overview (2-3 sentence overview of the contribution)
- [x] Feedback (2-3 paragraphs highlighting strengths of the paper. Please note anything that will be valuable for the authors to discuss / present at workshop)

**Comment by nniiicc** [comment]
Overall, I really enjoyed reading this and I was impressed by the amount of work that you've done over the last year. I'd honestly be happy to read more of this and hear a general update on the IMLS work at the workshop. If you're game we could even allocate some more time and talk through the conceptual model issues across cases you're looking at... 

Some general notes / feedback:
- Provide the reader with a little more guidance in the Introduction - The final sentence tells me why the case study is important, but I don't get a sense of the paper's overall structure. 
- The last two paragraphs of the Case section are gold - In future drafts I wouldn't wait to unpack and explain to the reader how this demonstrates vividly the tacking back and forth between conceptual and logical models in migration work. These distinctions are assumed to be rigid and clear - what your examples show is the opposite. 
- You write that the MBGNA's trajectory is similar to other NHMs... But, go a step further and tell the reader what this signifies... What does it mean to have further proof of this kind of chaotic migration from easily managed card catalogs? As you've written previously - this is more logically complex, but there are explanations about the institution, the data, etc that are explanatory (rather than the reader just concluding "databases are hard for museums") 
- In the final paragraph you discuss challenges to migration at the "meta-level" ... I think there is an opportunity to coin or re-purpose some language other than meta, meso, micro, etc ... These are going to get confusing with terminology like metadata for inexpert readers... and further it seems like an easy win for your contribution if you can say in the abstract "We introduce a set of migration patterns for databases that include X, Y, Z" 

Grammar notes:
- First sentence should just be "aspect"

**Comment by kfenlon** [comment]
Great paper! This is substantive work with strong potential impact. I look forward to hearing more about it.  I think the empirical work here will be an important complement to the more theoretical work offered in other papers in this workshop; in particular, because this paper is grounded in a case study, we glimpse the impact of labor considerations on modeling, which is hard to see when data models are considered in the abstract.

I agree with Nic's comments, and I have a few others:

- I like the tensions you reveal between models deployed for different intended _functions_: models tailored to support data entry; models that support standardization; interim models generated for purposes of conceptualization and schema-design; models oriented toward mapping and visualization. It will be interesting to see this brought into conversation with other papers at the workshop that raise tensions between _functional_ and _ontological_ goals of conceptual models.

- The implications you identify seem really useful and important. The solutions proposed are both visual, meant to support human reading and understanding of migrations, both granular and big-picture. I think it would be fascinating to be walked through the appendix EER diagrams, to make the methods and implications vivid for us. Would the visual approaches you have used usefully translate to, or how would these relate to semantic or machine-actionable provenance and workflow representations that are emerging standards for data curation?
